import Link from "next/link";
import PolicyLayout, { PolicySection } from "@/components/policies/PolicyLayout";
import { LEGAL_CONFIG } from "@/config/legal";
import { BASIC_MONTHLY_PRICE_LABEL, TRIAL_DURATION_LABEL } from "@/config/product";

export const metadata = { title: "Subscription Policy | Lankan Web Directory", description: "Subscription, trial, renewal and payment terms for Lankan Web Directory." };
const sections = [["pricing","Plans and pricing"],["trial","Free building and trial"],["renewal","Automatic renewal"],["payments","Payments"],["failed","Failed payments"],["changes","Changes and contact"]].map(([id,label])=>({id,label}));

export default function SubscriptionPolicyPage(){
 const { contactEmail }=LEGAL_CONFIG;
 return <PolicyLayout eyebrow="Clear recurring billing" title="Subscription Policy" introduction="This policy explains when publishing access begins, how the free trial works and how recurring subscription payments are handled." sections={sections}>
  <div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-stone-700"><strong className="text-[#BF283B]">Current Basic plan:</strong> {TRIAL_DURATION_LABEL} free trial where eligible, followed by {BASIC_MONTHLY_PRICE_LABEL} per month unless cancelled.</div>
  <PolicySection id="pricing" number="01" title="Plans and pricing"><p>Current prices, billing intervals, website limits and trial availability are displayed before checkout. Prices displayed in LKR are charged in LKR through Stripe unless checkout clearly states otherwise.</p><p>Your card issuer may apply international transaction, currency-conversion or other charges that we do not control.</p></PolicySection>
  <PolicySection id="trial" number="02" title="Free building and trial"><p>You may build and preview one website without payment. Publishing access requires an active trial or paid subscription.</p><p>Where offered, the free trial begins when you activate publishing through Stripe Checkout, not when you create your account. Trial eligibility is generally limited to one trial per customer. Unless cancelled before it ends, the trial automatically converts to a paid monthly subscription at the price shown during checkout.</p></PolicySection>
  <PolicySection id="renewal" number="03" title="Automatic renewal"><p>Subscriptions renew automatically at the billing interval shown during checkout until cancelled. By starting a subscription, you authorise Stripe to charge your selected payment method for recurring fees and applicable taxes.</p><p>You can prevent a future renewal by cancelling in accordance with our <Link className="font-bold text-[#BF283B] underline" href="/cancellation-policy">Cancellation Policy</Link>.</p></PolicySection>
  <PolicySection id="payments" number="04" title="Payments and plan access"><p>Stripe processes payments securely. We do not directly receive or store your complete card number or card security code.</p><p>Each plan includes a maximum number of websites. Current limits are displayed in the service. We may change prices or features for future billing periods after reasonable notice; changes do not retroactively alter a completed billing period.</p></PolicySection>
  <PolicySection id="failed" number="05" title="Failed and disputed payments"><p>If payment fails, Stripe may retry it and request an updated payment method. Publishing access and directory visibility may be restricted when payment is not completed or subscription access expires.</p><p>Contact us before initiating a payment dispute so we have an opportunity to investigate an incorrect charge. This does not restrict any right you have to contact your card issuer.</p></PolicySection>
  <PolicySection id="changes" number="06" title="Changes and contact"><p>We may update this policy and will publish the revised date. Questions about a subscription may be sent to <a className="font-bold text-[#BF283B] underline" href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p><p>Cancellation and refund rules are described separately in our <Link className="font-bold text-[#BF283B] underline" href="/cancellation-policy">Cancellation Policy</Link> and <Link className="font-bold text-[#BF283B] underline" href="/refund-policy">Refund Policy</Link>.</p></PolicySection>
 </PolicyLayout>;
}
