import Link from "next/link";
import PolicyLayout, { PolicySection } from "@/components/policies/PolicyLayout";
import { LEGAL_CONFIG } from "@/config/legal";

export const metadata = { title: "Cancellation Policy | Lankan Web Directory", description: "How to cancel a Lankan Web Directory subscription and what happens afterward." };
const sections=[["how","How to cancel"],["effective","When it takes effect"],["trial","Trial cancellation"],["after","After access ends"],["deletion","Account deletion"],["help","Help"]].map(([id,label])=>({id,label}));

export default function CancellationPolicyPage(){const {contactEmail}=LEGAL_CONFIG;return <PolicyLayout eyebrow="Stay in control" title="Cancellation Policy" introduction="You can cancel recurring billing at any time. This policy explains the effective date and what happens to your websites." sections={sections}>
 <div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-stone-700"><strong className="text-[#BF283B]">The essential point:</strong> cancellation stops future renewals. Access normally continues until the end of the current trial or paid billing period.</div>
 <PolicySection id="how" number="01" title="How to cancel"><p>Use “Manage subscription” in your account dashboard to open the Stripe Customer Portal and cancel. You may also request assistance by emailing <a className="font-bold text-[#BF283B] underline" href={`mailto:${contactEmail}`}>{contactEmail}</a> from the address associated with your account.</p></PolicySection>
 <PolicySection id="effective" number="02" title="When cancellation takes effect"><p>Unless otherwise stated during cancellation, it takes effect at the end of your current paid billing period. You may continue using subscription features until that date and no further renewal charge will be made.</p><p>Cancelling does not normally create a prorated refund for unused days. See our <Link className="font-bold text-[#BF283B] underline" href="/refund-policy">Refund Policy</Link>.</p></PolicySection>
 <PolicySection id="trial" number="03" title="Cancelling during a trial"><p>If you cancel before the trial ends, you will not be charged for the following paid period. Publishing access normally continues until the trial expiration date unless your Stripe account or customer portal states otherwise.</p></PolicySection>
 <PolicySection id="after" number="04" title="After publishing access ends"><p>Published and unlisted websites may become unavailable to visitors, and approved websites may be removed from directory results. You may retain limited account access to manage content or reactivate publishing.</p></PolicySection>
 <PolicySection id="deletion" number="05" title="Cancellation and account deletion"><p>Cancelling a subscription does not automatically delete your account or content. To request deletion of an account or personal information, contact us separately. Some records may be retained when required for accounting, security, dispute resolution or legal compliance.</p></PolicySection>
 <PolicySection id="help" number="06" title="Cancellation help"><p>If the customer portal is unavailable or you believe a renewal occurred after timely cancellation, email <a className="font-bold text-[#BF283B] underline" href={`mailto:${contactEmail}`}>{contactEmail}</a> promptly with your account email and payment date. Never send complete card details.</p></PolicySection>
 </PolicyLayout>}
