import PolicyLayout, { PolicySection } from "@/components/policies/PolicyLayout";
import { LEGAL_CONFIG, operatorDescription } from "@/config/legal";

export const metadata = { title: "Terms of Service | Lankan Web Directory", description: "Terms governing accounts, websites and directory listings on Lankan Web Directory." };
const sections = [
  ["agreement", "Agreement"], ["accounts", "Accounts"], ["service", "The service"],
  ["user-content", "Your content"], ["prohibited", "Prohibited content"], ["moderation", "Moderation"],
  ["availability", "Availability"], ["termination", "Suspension and termination"], ["liability", "Responsibility and liability"], ["contact", "Contact"],
].map(([id, label]) => ({ id, label }));

export default function TermsPage() {
  const { contactEmail, websiteUrl } = LEGAL_CONFIG;
  return <PolicyLayout eyebrow="The rules of the service" title="Terms of Service" introduction={`These Terms govern your use of ${LEGAL_CONFIG.serviceName}, including its website-building, publishing and business-directory services.`} sections={sections}>
    <div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-stone-700"><strong className="text-[#BF283B]">The essential point:</strong> you remain responsible for your business and everything you upload or publish through the service.</div>
    <PolicySection id="agreement" number="01" title="Agreement"><p>By creating an account, purchasing a subscription, publishing a website or otherwise using the service at {websiteUrl}, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the service.</p><p>These Terms form an agreement between you and {operatorDescription()}.</p></PolicySection>
    <PolicySection id="accounts" number="02" title="Eligibility and accounts"><p>You must be at least 18 years old and legally able to enter into an agreement. If you act for a business or organisation, you confirm that you are authorised to do so.</p><p>You must provide accurate information, protect your login details and notify us promptly if you suspect unauthorised access. You are responsible for activity performed through your account.</p></PolicySection>
    <PolicySection id="service" number="03" title="Website creation and directory listing"><p>You may create and preview a website before activating publishing. Once publishing access is active, a website may be accessible to anyone with its direct URL and may be shared by you.</p><p>A website does not automatically appear in the Lankan Web Directory. Directory inclusion requires submission, review and approval. Purchasing a subscription does not guarantee directory approval.</p></PolicySection>
    <PolicySection id="user-content" number="04" title="Your content and legal responsibility"><p>You are solely responsible for all text, photographs, illustrations, logos, links, contact details, claims and other material you upload, enter or publish. You must ensure it is accurate, lawful and appropriate and that you have every permission, licence and consent needed to use it.</p><p>By submitting content, you represent and warrant that you own it or have permission to reproduce and publish it. Our upload, preview, publishing or approval features do not mean that we have legally reviewed or approved your content.</p><p>You retain ownership of your content. You grant us a non-exclusive licence to host, copy, resize, format and display it as reasonably necessary to operate and promote the service.</p></PolicySection>
    <PolicySection id="prohibited" number="05" title="Prohibited content and conduct"><p>You must not publish content that infringes copyright, trademark, privacy or other rights; uses a person’s image or information without required permission; is defamatory, insulting, threatening, harassing, hateful, obscene or discriminatory; makes false or unsupported claims; impersonates another person or business; promotes unlawful activity; or contains malware or harmful links.</p><p>You must not use the service for scams, fraud, illegal goods or services, unauthorised access, interference with the platform, or collection of information in violation of applicable law.</p></PolicySection>
    <PolicySection id="moderation" number="06" title="Moderation, complaints and removal"><p>We may review, reject, restrict or remove content or listings that violate these Terms, create a legal or safety risk, misrepresent a business or are unsuitable for the directory. Directory approval is an administrative decision, not legal verification, and does not transfer responsibility for content to us.</p><p>Copyright, privacy, impersonation, defamation or other content complaints may be sent to <a className="font-bold text-[#BF283B] underline" href={`mailto:${contactEmail}`}>{contactEmail}</a>. Identify the affected website, disputed content and basis of the complaint.</p></PolicySection>
    <PolicySection id="availability" number="07" title="Service availability"><p>We aim to provide a reliable service but do not guarantee uninterrupted, permanent or error-free availability. Maintenance, provider outages, security events and circumstances outside our reasonable control may affect access.</p></PolicySection>
    <PolicySection id="termination" number="08" title="Suspension and termination"><p>We may suspend or terminate access for non-payment, fraud, security risks, misuse or material violation of these Terms. Where appropriate, we will provide notice and an opportunity to correct the issue. You may stop using the service and cancel under our Cancellation Policy.</p></PolicySection>
    <PolicySection id="liability" number="09" title="Responsibility and liability"><p>You are responsible for claims, losses, penalties and reasonable costs arising from your content, business activities or breach of these Terms. To the extent permitted by law, you agree to indemnify the service operator and its personnel against third-party claims arising from your content, infringement of another person’s rights or unlawful conduct.</p><p>To the maximum extent permitted by applicable law, we are not responsible for indirect or consequential losses, lost profits, lost opportunities, or losses caused by user content. Nothing in these Terms excludes a liability or consumer right that cannot lawfully be excluded.</p></PolicySection>
    <PolicySection id="contact" number="10" title="Changes and contact"><p>We may update these Terms and will publish the revised version and update its date. Material changes may also be communicated through the service or by email.</p><p>Questions or legal notices may be sent to <a className="font-bold text-[#BF283B] underline" href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p></PolicySection>
  </PolicyLayout>;
}
