import PolicyLayout, { PolicySection } from "@/components/policies/PolicyLayout";
import { LEGAL_CONFIG } from "@/config/legal";

export const metadata = { title: "Refund Policy | Lankan Web Directory", description: "Refund eligibility and request process for Lankan Web Directory subscriptions." };
const sections=[["general","General rule"],["eligible","Eligible refunds"],["rejection","Directory rejection"],["request","Requesting a refund"],["processing","Refund processing"],["rights","Your rights"]].map(([id,label])=>({id,label}));

export default function RefundPolicyPage(){const {contactEmail}=LEGAL_CONFIG;return <PolicyLayout eyebrow="Fair and transparent" title="Refund Policy" introduction="This policy explains when subscription payments may be refunded and how to ask us to review a charge." sections={sections}>
 <div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-stone-700"><strong className="text-[#BF283B]">Request period:</strong> contact us within seven days of the relevant charge so we can investigate promptly.</div>
 <PolicySection id="general" number="01" title="General rule"><p>Subscription payments are normally non-refundable once a paid billing period begins because publishing and hosting access are made available immediately. Cancelling stops future renewals but does not automatically produce a prorated refund for remaining days.</p></PolicySection>
 <PolicySection id="eligible" number="02" title="When we may provide a refund"><p>We may issue a full or partial refund when you were charged after cancelling before the renewal deadline; a duplicate or clearly incorrect charge occurred; a technical error attributable to our service prevented meaningful use for a substantial part of the billing period; or a refund is required by applicable law.</p></PolicySection>
 <PolicySection id="rejection" number="03" title="Directory-listing rejection"><p>If your first submitted website receives a final rejection and we do not permit or cannot reasonably support corrections, you may request a refund of the initial subscription payment within seven days of receiving that decision.</p><p>A refund may be refused where the submission violated our Terms, involved fraud or abuse, or the subscription was already used to publish another website. Directory approval is separate from direct website publishing access.</p></PolicySection>
 <PolicySection id="request" number="04" title="Requesting a refund"><p>Email <a className="font-bold text-[#BF283B] underline" href={`mailto:${contactEmail}?subject=Refund%20request`}>{contactEmail}</a> within seven days of the charge. Include your account email, payment date and reason. Do not send your complete card number or security code.</p></PolicySection>
 <PolicySection id="processing" number="05" title="How refunds are processed"><p>Approved refunds are returned through Stripe to the original payment method. Bank and card-processing times are outside our control. Exchange-rate movements or card-issuer fees may mean the amount received differs from an earlier local-currency equivalent.</p></PolicySection>
 <PolicySection id="rights" number="06" title="Mandatory rights"><p>This policy does not limit a refund, cancellation or consumer right that cannot lawfully be excluded. We assess requests fairly based on the circumstances and applicable law.</p></PolicySection>
 </PolicyLayout>}
